"""Generate the data-provenance table for the manual, straight from the
pipeline config so it can never drift from what is actually downloaded.

Reads:
  pipeline/variables.py   -- the variable registry (fields, levels, units)
  pipeline/fetch_gfs.py    -- the NOMADS endpoint + file pattern
  data/<var>.json          -- the cycle/run time and grid size actually present

Writes:
  docs/data_sources.tex    -- a LaTeX table fragment included by manual.tex
"""

from __future__ import annotations

import importlib.util
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
PIPE = ROOT / "pipeline"
DATA = ROOT / "data"
OUT = ROOT / "docs" / "data_sources.tex"


def load_module(path: Path, name: str):
    spec = importlib.util.spec_from_file_location(name, path)
    mod = importlib.util.module_from_spec(spec)
    sys.modules[name] = mod          # dataclass introspection needs this
    spec.loader.exec_module(mod)
    return mod


def tex_escape(s: str) -> str:
    s = s.replace("&", r"\&").replace("%", r"\%").replace("_", r"\_")
    s = s.replace("°", r"\textdegree{}")
    s = s.replace("²", r"\textsuperscript{2}")
    return s


def human_level(params: dict) -> str:
    for k in params:
        if k.startswith("lev_"):
            lev = k[len("lev_"):]
            lev = lev.replace("_", " ")
            lev = lev.replace("(considered as a single layer)", "(single layer)")
            return lev
    return "—"


def nomads_vars(params: dict) -> str:
    return ", ".join(k[len("var_"):] for k in params if k.startswith("var_"))


def main() -> int:
    variables = load_module(PIPE / "variables.py", "variables")
    fetch = load_module(PIPE / "fetch_gfs.py", "fetch_gfs")

    # Cycle + grid from whatever metadata is actually present on disk.
    run_time, width, height, res = "(not built)", "?", "?", 0.5
    mslp_json = DATA / "mslp.json"
    if mslp_json.exists():
        m = json.loads(mslp_json.read_text())
        run_time = m.get("run_time", run_time)
        width, height = m.get("width", "?"), m.get("height", "?")
    runjson = DATA / "raw" / "run.json"
    if runjson.exists():
        res = json.loads(runjson.read_text()).get("resolution_deg", res)

    rows = []
    for v in variables.VARIABLES:
        keys = ", ".join(v.grib_keys)
        rows.append(
            f"  \\texttt{{{tex_escape(v.name)}}} & {tex_escape(v.label)} & "
            f"\\texttt{{{tex_escape(nomads_vars(v.nomads_params))}}} & "
            f"{tex_escape(human_level(v.nomads_params))} & "
            f"\\texttt{{{tex_escape(keys)}}} & {tex_escape(v.units)} \\\\")

    endpoint = fetch.NOMADS
    body = "\n".join(rows)
    tex = f"""% AUTO-GENERATED by docs/gen_data_sources.py -- do not edit by hand.
\\begin{{table}}[h]
\\centering
\\footnotesize
\\setlength{{\\tabcolsep}}{{4pt}}
\\begin{{tabular}}{{@{{}}l p{{2.6cm}} l p{{2.7cm}} l l@{{}}}}
\\toprule
\\textbf{{Layer}} & \\textbf{{Quantity}} & \\textbf{{NOMADS var}} & \\textbf{{Level}} & \\textbf{{GRIB key}} & \\textbf{{Units}} \\\\
\\midrule
{body}
\\bottomrule
\\end{{tabular}}
\\caption{{Every data layer ingested by meteoearth, generated directly from
\\texttt{{pipeline/variables.py}} by \\texttt{{docs/gen\\_data\\_sources.py}}.
All layers come from a single source: the NOAA NCEP GFS model, downloaded as
GRIB2 subsets from the NOMADS filter endpoint
\\texttt{{{tex_escape(endpoint)}}} at {res}\\textdegree{{}} resolution, analysis hour f000.
Current cycle: \\texttt{{{tex_escape(run_time)}}}; global grid {width}\\,$\\times$\\,{height}.}}
\\label{{tab:data}}
\\end{{table}}
"""
    OUT.write_text(tex)
    print(f"wrote {OUT.relative_to(ROOT)} ({len(variables.VARIABLES)} layers)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
