"""Generate the data-provenance tables for the manual, straight from the built
data so they can never drift from what is actually shipped.

Reads:
  pipeline/variables.py   -- canonical variable registry (labels, units, kind)
  data/index.json         -- the sources actually built, each with its run time,
                             resolution, forecast steps, and variable coverage

Writes:
  docs/data_sources.tex   -- two LaTeX table fragments included by manual.tex
"""

from __future__ import annotations

import importlib.util
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
PIPE = ROOT / "pipeline"
DATA = ROOT / "data"
OUT = ROOT / "docs" / "data_sources.tex"


def load_module(path: Path, name: str):
    spec = importlib.util.spec_from_file_location(name, path)
    mod = importlib.util.module_from_spec(spec)
    sys.modules[name] = mod          # dataclass introspection needs this
    spec.loader.exec_module(mod)
    return mod


def tex(s: str) -> str:
    s = str(s)
    s = s.replace("&", r"\&").replace("%", r"\%").replace("_", r"\_")
    s = s.replace("°", r"\textdegree{}").replace("²", r"\textsuperscript{2}")
    return s


def main() -> int:
    variables = load_module(PIPE / "variables.py", "variables")
    index = json.loads((DATA / "index.json").read_text()) if (DATA / "index.json").exists() else {"sources": []}
    sources = index.get("sources", [])
    have = {s["id"]: {v["name"] for v in s["variables"]} for s in sources}

    # ---- Table 1: the source models ----
    src_rows = []
    for s in sources:
        steps = s.get("times", [])
        span = f"f000--f{steps[-1]['forecast_hour']:03d}/{(steps[1]['forecast_hour']-steps[0]['forecast_hour']) if len(steps) > 1 else 0}h" if steps else "—"
        src_rows.append(
            f"  \\texttt{{{tex(s['id'])}}} & {tex(s['label'])} & "
            f"{s['resolution_deg']}\\textdegree{{}} & {len(s['variables'])} & "
            f"{tex(span)} & \\texttt{{{tex(s.get('run_time','?'))}}} \\\\")

    # ---- Table 2: canonical variables and which models provide them ----
    ids = [s["id"] for s in sources]
    head = " & ".join(f"\\textbf{{{tex(i)}}}" for i in ids)
    var_rows = []
    for v in variables.VARIABLES:
        marks = " & ".join("\\checkmark" if v.name in have.get(i, set()) else "--" for i in ids)
        var_rows.append(
            f"  \\texttt{{{tex(v.name)}}} & {tex(v.label)} & {tex(v.units)} & {marks} \\\\")

    colspec = "@{}l p{3.2cm} l " + " ".join("c" for _ in ids) + "@{}"
    body = f"""% AUTO-GENERATED by docs/gen_data_sources.py -- do not edit by hand.
\\begin{{table}}[h]
\\centering
\\footnotesize
\\setlength{{\\tabcolsep}}{{5pt}}
\\begin{{tabular}}{{@{{}}l p{{3.0cm}} l c l l@{{}}}}
\\toprule
\\textbf{{Source}} & \\textbf{{Model}} & \\textbf{{Res.}} & \\textbf{{Vars}} & \\textbf{{Steps}} & \\textbf{{Cycle}} \\\\
\\midrule
{chr(10).join(src_rows)}
\\bottomrule
\\end{{tabular}}
\\caption{{The global forecast models meteoearth ingests, generated from
\\texttt{{data/index.json}} by \\texttt{{docs/gen\\_data\\_sources.py}}. Each model
is fetched independently from its own provider (NOMADS, ECMWF open data, and the
MSC hpfx server) at its native resolution, for the analysis hour through a
two-day forecast.}}
\\label{{tab:sources}}
\\end{{table}}

\\begin{{table}}[h]
\\centering
\\footnotesize
\\setlength{{\\tabcolsep}}{{6pt}}
\\begin{{tabular}}{{{colspec}}}
\\toprule
\\textbf{{Layer}} & \\textbf{{Quantity}} & \\textbf{{Units}} & {head} \\\\
\\midrule
{chr(10).join(var_rows)}
\\bottomrule
\\end{{tabular}}
\\caption{{Canonical layers and which models provide each one. Where a model does
not publish a field (e.g.\\ ECMWF open data has no plain CAPE or instantaneous
precipitation, GEM no precipitable water), the corresponding overlay is greyed
out when that model is selected.}}
\\label{{tab:coverage}}
\\end{{table}}
"""
    OUT.write_text(body)
    print(f"wrote {OUT.relative_to(ROOT)} ({len(sources)} sources, {len(variables.VARIABLES)} layers)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
